runtime: python39
service: rasa-app
handlers:
- url: /
  script: manage.py runserver
- url: /admin/ruby_admin/
  script: manage.py runserver
  admin_handlers: yes
  static_dir: /admin/ruby_admin/static
  upload_url: /admin/ruby_admin/upload
  login: admin

env_variables:
  RASA_MODEL_DIRECTORY: .