# Generated by Django 4.1.10 on 2023-09-02 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('intent', models.CharField(default='intent name', max_length=100, primary_key=True, serialize=False, verbose_name='Intent')),
                ('message', models.CharField(default='your message', max_length=1000, verbose_name='User Message')),
                ('response', models.CharField(default='new response', max_length=1000, verbose_name='AI Response')),
                ('createdate', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date')),
                ('status', models.CharField(choices=[('W', 'Waiting for Approval'), ('O', 'On Hold'), ('A', 'Approved'), ('R', 'Rejected')], default='W', max_length=100)),
            ],
        ),
    ]
