# Generated by Django 4.1.10 on 2023-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('Waiting for Approval', 'Waiting for Approval'), ('On Hold', 'On Hold'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='W', max_length=100),
        ),
    ]
